### ISSUE TITLE
Audio Deepfake detection models

### ISSUE THREAD

**Issue by klh5** [alan-turing-institute/ARC-Speech-Synthesis#10]
Identify and implement (hopefully re-use) a SOTA (or close to SOTA) audio deepfake detection model.

The plan here is to use this model initially for ID-ing voice synthesis models, by making use of the intermediate speech representation.

Possible models:

- [ASSERT](https://github.com/jefflai108/ASSERT) 
- [RawNet2](https://github.com/asvspoof-challenge/2021/tree/main/LA/Baseline-RawNet2)

**Comment by alexeatscake** [comment]
At the moment we are looking into RawNet2.
There is a good collection of baseline models on this GitHub repository. https://github.com/asvspoof-challenge/2021
